name: todo_sqlite
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  path_provider: ^2.1.5
  sqflite: ^2.3.3+1
  yandex_maps_mapkit_lite: ^4.9.0-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
