name: todo_sqlite
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.2
  intl: ^0.19.0
  location: ^7.0.1
  path_provider: ^2.1.5
  sqflite: ^2.3.3+1
  yandex_mapkit: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
